# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

use_frameworks!

target 'Sequences' do

pod 'RxSwift', '~> 2.0.0-alpha'
pod 'RxCocoa', '~> 2.0.0-alpha'

end

target 'SequencesTests' do

end

